---

- name: "fetch plex"
  get_url:
    url={{ plex_url_i386 }}
    sha256sum={{ plex_sha256_i386 }}
    dest=/var/cache/apt/archives/plex.deb

####################################################################
# workaround for #2430                                             #
# see: https://github.com/ansible/ansible-modules-core/issues/2430 #
- name: "check installed plex version"                             #
  shell: dpkg-query --show plexmediaserver | awk '{print $2}'      #
  register: plex_installed_version                                 #
  changed_when: false                                              #
                                                                   #
- name: "fetch deb file version"                                   #
  command: dpkg -f /var/cache/apt/archives/plex.deb VERSION        #
  register: plex_deb_version                                       #
  changed_when: false                                              #
####################################################################

- name: "install plex"
  apt:
    deb=/var/cache/apt/archives/plex.deb
    update_cache=false
    state=present
  when: plex_deb_version.stdout != plex_installed_version.stdout
  notify:
    - restart plex

- name: "fetch subliminal plugin"
  get_url:
    url={{ plex_subliminal_plugin_url }}
    dest=/var/cache/apt/archives/Subliminal.bundle-master.zip
    sha256sum={{ plex_subliminal_plugin_sha256 }}

- name: "check if subliminal is installed"
  failed_when: false
  changed_when: subliminal_installed.rc != 0
  command: stat "{{ plex_plugin_path }}/Subliminal.bundle"
  register: subliminal_installed

- name: "install subliminal"
  when: subliminal_installed.rc != 0
  unarchive:
    copy=no
    src=/var/cache/apt/archives/Subliminal.bundle-master.zip
    dest="{{ plex_plugin_path }}"

- name: "fix subliminal plugin path"
  when: subliminal_installed.rc != 0
  command: |
    mv "{{ plex_plugin_path }}/Subliminal.bundle-master"
       "{{ plex_plugin_path }}/Subliminal.bundle"
  notify:
    - restart plex

- name: "set up auto-refresh with cron"
  cron:
    job="curl http://localhost:32400/library/sections/{{ plex_tv_show_section }}/refresh?force=1"
    name="auto-refresh with cron"
    hour="*/2"
    user="renan"
    state="present"
