- name: "install python3 & python3-pip"
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
    state=latest
  with_items:
    - python3
    - python3-pip

- name: "install pyenv & pyenv-virtualenv"
  shell: |
    pip3 install --egg pyenv
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"

    pyenv install 3.6.2
