- name: install packages
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
  with_items:
    - emacs24-nox
    - bash-completion
    - build-essential
    - calibre
    - curl
    - dnsutils
    - ftp
    - git
    - vim
    - wget
    - p7zip-full
    - mkvtoolnix
