- name: "set up required apt-keys"
  apt_key:
    id="{{ item.id }}"
    keyserver="{{ item.keyserver }}"
    state="present"
  with_items:
    - description: "spotify"
      keyserver: "keyserver.ubuntu.com"
      id: "0DF731E45CE24F27EEEB1450EFDC8610341D9410"
    - description: "telegram"
      keyserver: "keyserver.ubuntu.com"
      id: "A3D8A366869FE2DC5FFD79C36A9653F936FD5529"

- name: "set preferences"
  copy:
    dest: /etc/apt/preferences
    content: |
      Package: *
      Pin: release a=stable
      Pin-Priority: 900

      Package: *
      Pin: release a=testing
      Pin-Priority: -10

- name: "set up required repositories"
  apt_repository:
    repo="{{ item }}"
    state="present"
    update_cache="yes"
    mode="644"
  with_items:
    # We will use debian testing
    - deb http://repository.spotify.com stable non-free
    - deb http://ftp.br.debian.org/debian testing main non-free contrib
    - deb http://ppa.launchpad.net/atareao/telegram/ubuntu xenial main

- name: "install essential"
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
  with_items:
    - ansible
    - aspell-pt-br
    - bash-completion
    - build-essential
    - curl
    - dnsutils
    - g++-multilib
    - gcc-multilib
    - git
    - gnupg
    - gnupg-agent
    - inotify-tools
    - jq
    - libcurl3
    - libgraphicsmagick1-dev
    - libreadline7
    - libsqlite3-dev
    - libssl-dev
    - libtool-bin
    - libncursesw5-dev
    - libxml2-utils # needed to pretty print xml @ Emacs
    - mysql-server
    - ncftp
    - openssh-server
    - redis-server
    - silversearcher-ag
    - socat
    - ssh
    - wget
    - wordnet
    - xclip
    - xdg-utils
