- name: "set up required apt-keys"
  apt_key:
    id="{{ item.id }}"
    keyserver="{{ item.keyserver }}"
    state="present"
  with_items:
    - description: "spotify"
      keyserver: "keyserver.ubuntu.com"
      id: "BBEBDCB318AD50EC6865090613B00F1FD2C19886"
    - description: "spideroak"
      keyserver: "keyserver.ubuntu.com"
      id: "573E3D1C51AE1B3D"
    - description: "git core"
      keyserver: "keyserver.ubuntu.com"
      id: "E1DD270288B4E6030699E45FA1715D88E1DF1F24"
    - description: "telegram"
      keyserver: "keyserver.ubuntu.com"
      id: "A3D8A366869FE2DC5FFD79C36A9653F936FD5529"

- name: "set up required repositories"
  apt_repository:
    repo="{{ item }}"
    state="present"
    update_cache="yes"
    mode="644"
  with_items:
    # We will use debian testing
    - deb http://ftp.br.debian.org/debian testing main non-free contrib
    - deb http://repository.spotify.com stable non-free
    - deb http://ppa.launchpad.net/git-core/ppa/ubuntu trusty main
    - deb http://ppa.launchpad.net/atareao/telegram/ubuntu xenial main

- name: "upgrade packages"
  apt: upgrade="full"

- name: "install essential"
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
  with_items:
    - ansible
    - aspell-pt-br
    - bash-completion
    - build-essential
    - curl
    - dnsutils
    - g++-multilib
    - gcc-multilib
    - git
    - gnupg
    - gnupg-agent
    - inotify-tools
    - jq
    - libcurl3
    - libgraphicsmagick1-dev
    - libreadline7
    - libsqlite3-dev
    - libssl-dev
    - libtool-bin
    - libcursesw5-dev
    - libxml2-utils # needed to pretty print xml @ Emacs
    - ncftp
    - openssh-server
    - redis-server
    - silversearcher-ag
    - socat
    - ssh
    - wget
    - wordnet
    - xclip
    - xdg-utils
