- name: "set up required apt-keys"
  apt_key:
    id="{{ item.id }}"
    keyserver="{{ item.keyserver }}"
    state="present"
  with_items:
    - description: "spotify"
      keyserver: "keyserver.ubuntu.com"
      id: "BBEBDCB318AD50EC6865090613B00F1FD2C19886"
    - description: "spideroak"
      keyserver: "keyserver.ubuntu.com"
      id: "573E3D1C51AE1B3D"

- name: "set up required repositories"
  apt_repository:
    repo="{{ item }}"
    state="present"
    update_cache="yes"
    mode="644"
  with_items:
    - deb http://repository.spotify.com stable non-free
    - ppa:git-core/ppa
    - ppa:ansible/ansible
    - ppa:atareao/telegram
#    - ppa:elementary-os/unstable-upstream
#    - ppa:mpstark/elementary-tweaks-daily

- name: "install essential"
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
    state=latest
  with_items:
    - ansible
    - aspell-pt-br
    - bash-completion
    - build-essential
    - curl
    - dnsutils
    - g++-multilib
    - gcc-multilib
    - git
    - gnupg
    - gnupg-agent
    - inotify-tools
    - jid
    - jq
    - libcurl3
    - libreadline6
    - libsqlite3-dev
    - libssl-dev
    - libxml2-utils # needed to pretty print xml @ Emacs
    - ncftp
    - openssh-server
    - python-pip
    - redis-server
    - silversearcher-ag
    - socat
    - ssh
    - wget
    - wordnet
    - xclip
    - xdg-utils
