- name: "copy config file"
  register: setupvars
  copy:
    src="setupVars.conf"
    dest="/etc/pihole/setupVars.conf"

- name: "run automagic installation"
  register: pihole_installed
  shell: curl -L https://install.pi-hole.net | bash /dev/stdin --unattended
  args:
    creates: /usr/local/bin/pihole

- name: "install unbound"
  apt:
    name="unbound"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"

- name: "add pihole conf file"
  register: pi_hole_conf
  copy:
    src: "pi-hole.conf"
    dest: "/etc/unbound/unbound.conf.d/pi-hole.conf"

- name: "add dns entries"
  register: home_dns_conf
  copy:
    src: "home.conf"
    dest: "/etc/unbound/unbound.conf.d/home.conf"

- name: "ensure unbound is correctly configured"
  when: "home_dns_conf.changed or pi_hole_conf.changed"
  command: unbound-checkconf

- name: "restart pihole dns"
  when: "home_dns_conf.changed or pi_hole_conf.changed"
  command: pihole restartdns

- name: "enable & start unbound"
  when: "home_dns_conf.changed or pi_hole_conf.changed"
  service:
    name="{{ item }}"
    state="restarted"
    enabled="yes"
  with_items:
    - "unbound"
    - "unbound-resolvconf"
