- name: "download hstr"
  get_url:
    url='https://github.com/dvorka/hstr/releases/download/1.23/hh-1.23-src.tgz'
    dest='/tmp/hh.tgz'
  register: hstr

- name: "untar hh"
  when: hstr.changed
  unarchive:
    src='/tmp/hh.tgz'
    dest='/tmp/'
    copy=no

- name: "complie & install hh"
  shell: './configure && make && make install'
  args:
    chdir: '/tmp/hstr'
    creates: '/usr/local/bin/hh'


- name: "link dotfiles"
  become: false
  command: "{{ code_dir }}/linuxsetup/desktop/scripts/setup_dotfiles"
  changed_when: false

- name: "configure git"
  become: false
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - { name: "user.name", value: "Milhouse" }
    - { name: "user.email", value: "renanranelli@gmail.com" }
    - { name: "user.signingKey", value: "BDD12B22" }
    - { name: "push.default", value: "simple" }
    - { name: "commit.template", value: "/home/{{ local_user }}/.gitcommittemplate" }
    - { name: "commit.gpgsign", value: "true" }
    - { name: "github.user", value: "rranelli" }
    - { name: "github.token", value: "{{ github_oauth_token }}" }
    - { name: "github.oauth-token", value: "{{ github_oauth_token }}" }


- name: "copy .authinfo.gpg file for magithub"
  become: false
  copy:
    src=".authinfo.gpg"
    dest="~/.authinfo.gpg"

- name: "download all of your github code"
  become: false
  shell: |
    env CODE_DIR={{ code_dir }} \
        {{ code_dir }}/linuxsetup/desktop/scripts/gitmulticast.sh clone && \
          touch "{{ code_dir }}/.fetched"
  args:
    chdir: "{{ code_dir }}"
    creates: "{{ code_dir }}/.fetched"

- file: path=/etc/resolvconf/resolv.conf.d state=directory
- name: "configure resolvconf to search for hosts @ Xerpa"
  copy:
    src=resolvconf-base
    dest=/etc/resolvconf/resolv.conf.d/base
