- name: "install asdf"
  become: false
  git:
    repo="https://github.com/asdf-vm/asdf.git"
    dest="~/.asdf"
    version="v0.4.1"

#
## Erlang

- name: "install asdf's Erlang plugin"
  become: false
  command: "~/.asdf/bin/asdf plugin-add erlang"
  args:
    creates: "~/.asdf/plugins/erlang/LICENSE"

- name: "install Erlang {{ erlang_version }}"
  become: false
  command: "~/.asdf/bin/asdf install erlang {{ erlang_version }}"
  args:
    creates: "~/.asdf/installs/erlang/{{ erlang_version }}/bin/erl"

- name: "use global Erlang {{ erlang_version }}"
  become: false
  command: "~/.asdf/bin/asdf global erlang {{ erlang_version }}"
  changed_when: false

#
## Elixir

- name: "install asdf's Elixir plugin"
  become: false
  command: "~/.asdf/bin/asdf plugin-add elixir"
  args:
    creates: "~/.asdf/plugins/elixir/LICENSE"

- name: "install Elixir {{ elixir_version }}"
  become: false
  command: "~/.asdf/bin/asdf install elixir {{ elixir_version }}"
  args:
    creates: "~/.asdf/installs/elixir/{{ elixir_version }}/bin/elixir"

- name: "use global Elixir {{ elixir_version }}"
  become: false
  command: "~/.asdf/bin/asdf global elixir {{ elixir_version }}"
  changed_when: false

- name: "set up mix completion"
  copy:
    src=mix-completion
    dest=/etc/bash_completion.d/mix
    mode=755
