---

- name: "ensure jessie-backports repository is available"
  apt_repository:
    repo="deb http://http.debian.net/debian jessie-backports main"
    state="present"
    update_cache="yes"

- name: "install znc from jessie-backports"
  apt:
    name=znc
    state="present"
    default_release=jessie-backports
    update_cache="yes"
    cache_valid_time=86400

- name: "add znc system file"
  copy:
    src=znc.service
    dest=/etc/systemd/system/znc.service

- name: "enable znc service"
  service:
    name=znc
    enabled=true
  notify:
    - systemd reload

- name: "configure znc"
  command: cat "you have to run `znc --makeconf` manually!"
  args:
    creates: /home/renan/.znc/configs/znc.conf
