- name: "install ruby-build dependencies"
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev

- name: "install rbenv & friends"
  become: false
  shell: |
    curl https://raw.githubusercontent.com/fesplugas/rbenv-installer/master/bin/rbenv-installer | bash
  args:
    creates: "{{ rbenv_home }}"

- name: "install ruby {{ ruby_version }}"
  become: false
  shell: |
    {{rbenv_home}}/bin/rbenv install "{{ ruby_version }}"
    {{rbenv_home}}/bin/rbenv global  "{{ ruby_version }}"
  args:
    creates: "{{ rbenv_home }}/versions/{{ ruby_version }}/bin/ruby"
