---

- name: "install nginx"
  apt:
    pkg=nginx
    state=installed
    update_cache=true
    cache_valid_time=86400

- name: "copy vhosts"
  template:
    src="{{ item }}"
    dest="/etc/nginx/{{ item }}"
    mode=0644
  with_items:
    - .htpasswd
    - sites-enabled/calibre
    - sites-enabled/monit
    - sites-enabled/plex
    - sites-enabled/root
    - sites-enabled/torrent
  notify:
    - restart nginx
