---

- hosts: media
  become: yes
  tasks:
    - name: install packages
      apt:
        pkg={{ item }}
        state=installed
        update_cache=true
      with_items:
        - bash-completion
        - build-essential
        - calibre
        - curl
        - deluge-console
        - deluge-web
        - deluged
        - dnsutils
        - ftp
        - git
        - monit
        - nginx
        - vim
        - wget

    ## TODO: no sleep, ever. http://askubuntu.com/questions/47311/how-do-i-disable-my-system-from-going-to-sleep
    ## TODO: generate locale. /etc/locale.conf, /usr/sbin/locale-gen as root
    ## TODO: noip2 installation & configuration
    ## TODO: beets
    ## TODO: nginx files
    ## TODO: monit files
    ## TODO: calibre server
    ## TODO: configure deluge daemon, enable and username/password
    ## TODO: configure deluge-web, enable it and username/password
    ## TODO: configure podnapsi subtitles

    - name: "fetch plex"
      get_url:
        url=https://downloads.plex.tv/plex-media-server/0.9.15.6.1714-7be11e1/plexmediaserver_0.9.15.6.1714-7be11e1_i386.deb
        dest=/var/cache/apt/archives/plex.deb
        sha256sum=ac5f7daaf6054fd71efe6d48a1ecc65b4a5ecce60e5a6d51de0b430cec3fdadb

    - name: "install plex"
      apt:
        deb=/var/cache/apt/archives/plex.deb
        state=present
      notify:
        - start plex

  handlers:
    - name: start plex
      service:
        name=plexmediaserver
        state=started
