- name: "install vpn required packages"
  apt:
    name="vpnc"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"

- name: "vnpc default conf file"
  copy:
    src="etc/vpnc/default.conf"
    dest="/etc/vpnc/default.conf"

- file: path="/etc/resolvconf/resolv.conf.d/" state="directory"
- name: "add resolv.conf to search ipa.corp.telnyx.com"
  copy:
    src="etc/resolvconf/resolv.conf.d/telnyx"
    dest="/etc/resolvconf/resolv.conf.d/telnyx"
