- name: "setup gsettings"
  become: false
  shell: |
    diff <(gsettings get {{item.setting}}) \
         <(gsettings set {{item.setting}} "{{ item.value }}"; \
           gsettings get {{item.setting}})
  args:
    executable: /bin/bash
  register: gsetting
  changed_when: gsetting.rc != 0
  failed_when: false
  with_items:
    - setting: "org.gnome.crypto.cache gpg-cache-method"
      value: "'timeout'"
    - setting: "org.gnome.crypto.cache gpg-cache-ttl"
      value: "10800"

    - setting: "org.gnome.Terminal.Legacy.Settings default-show-menubar"
      value: "false"
    - setting: "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ next-tab"
      value: "'<Control><Shift>Right'"
    - setting: "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ prev-tab"
      value: "'<Control><Shift>Left'"


    - setting: "org.gnome.desktop.peripherals.touchpad tap-to-click"
      value: "true"
    - setting: "org.gnome.desktop.peripherals.keyboard repeat-interval"
      value: "17"
    - setting: "org.gnome.desktop.peripherals.keyboard delay"
      value: "202"
    - setting: "org.gnome.desktop.input-sources xkb-options"
      value: "['ctrl:nocaps', 'compose:rctrl']"

    - setting: "org.gnome.mutter workspaces-only-on-primary"
      value: "false"
    - setting: "org.gnome.shell.overrides workspaces-only-on-primary"
      value: "false"
    - setting: "org.gnome.mutter dynamic-workspaces"
      value: "true"
    - setting: "org.gnome.shell.overrides dynamic-workspaces"
      value: "true"
    - setting: "org.gnome.desktop.wm.keybindings switch-to-workspace-up"
      value: "['<Super>Left']"
    - setting: "org.gnome.desktop.wm.keybindings switch-to-workspace-down"
      value: "['<Super>Right']"
    - setting: "org.gnome.desktop.wm.keybindings move-to-workspace-up"
      value: "['<Super><Alt>Left']"
    - setting: "org.gnome.desktop.wm.keybindings move-to-workspace-down"
      value: "['<Super><Alt>Right']"

    - setting: "org.gnome.desktop.interface clock-show-date"
      value: "true"

    - setting: "org.gnome.desktop.wm.keybindings minimize"
      value: "['<Super>h']"
    - setting: "org.gnome.desktop.wm.keybindings maximize"
      value: "[]"
    - setting: "org.gnome.desktop.wm.keybindings toggle-maximized"
      value: "['<Super>Up']"
    - setting: "org.gnome.desktop.wm.keybindings toggle-fullscreen"
      value: "@as ['<Super><Alt>Up']"
    - setting: "org.gnome.desktop.wm.keybindings close"
      value: "['<Super>q']"
    - setting: "org.gnome.desktop.wm.keybindings panel-main-menu"
      value: "['<Super>space']"
    - setting: "org.gnome.settings-daemon.plugins.media-keys search"
      value: "'<Super>space'"
    - setting: "org.gnome.shell.keybindings toggle-overview"
      value: "['<Super>space']"
    - setting: "org.gnome.shell.keybindings toggle-application-view"
      value: "['<Super>a']"
    - setting: "org.gnome.mutter.keybindings toggle-tiled-left"
      value: "['<Control><Super>Left']"
    - setting: "org.gnome.mutter.keybindings toggle-tiled-right"
      value: "['<Control><Super>Right']"
