- name: "desktop application packages"
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
  with_items:
    - calibre
    - deluge
    - libreoffice
    - spotify-client
    - telegram
    - libappindicator3-1
    - ttf-ancient-fonts # adds fonts needed by emacs

- name: "remove unnecessary dirs @ home"
  file:
    path="/home/{{ local_user }}/{{ item }}"
    state="absent"
  with_items: ["Documents","Music","Videos","Templates","Public","Desktop"]

- name: "firefox"
  include_tasks: "firefox.yml"

- name: "dropbox"
  include_tasks: "dropbox.yml"

- name: "slack"
  include_tasks: "slack.yml"

- name: "gsettings"
  include_tasks: "gsettings.yml"

- name: "peek"
  include_tasks: 'peek.yml'

- name: "skype"
  include_tasks: 'skype.yml'
