- name: "desktop application packages"
  apt:
    name="{{ item }}"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
  with_items:
    - calibre
    - deluge
    - libreoffice
    - spotify-client
    - telegram
    - libappindicator3-1
    - ttf-ancient-fonts # adds fonts needed by emacs

- name: "check if slack is installed"
  stat: path="/usr/bin/slack"
  register: slack
  changed_when: slack.stat.exists == False

- name: "download slack"
  when: slack.changed
  get_url:
    url="{{ slack_deb_url }}"
    dest="/tmp/slack.deb"
  register: slack_download

- name: "install slack"
  when: slack_download.changed
  apt:
    deb="/tmp/slack.deb"
    state="present"

- name: "check if SpiderOak is installed"
  command: dpkg-query --show spideroakone
  register: spideroak
  changed_when: spideroak.rc != 0
  failed_when: false

- name: "download SpiderOak's deb file"
  when: spideroak.changed
  get_url:
    url="https://spideroak.com/getbuild?platform=ubuntu&arch=x86_64"
    dest="/tmp/spideroak.deb"

- name: "install spideroak"
  when: spideroak.changed
  apt:
    deb="/tmp/spideroak.deb"
    state="present"

- file: path="~/.fonts" state="directory"
  become: false

- name: "install fira code"
  become: false
  shell: |
    wget https://github.com/tonsky/FiraCode/releases/download/1.101/FiraCode_1.101.zip
    unzip FiraCode*.zip
    cp FiraCode*/*.otf ~/.fonts
    fc-cache -f -v
    rm -rf FiraCode*/ FiraCode*.zip
  args:
    creates: "~/.fonts/FiraCode-Retina.otf"

- name: "install source-code-pro"
  become: false
  shell: |
    wget https://github.com/adobe-fonts/source-code-pro/archive/1.017R.zip
    unzip 1.017R.zip
    cp source-code-pro-1.017R/OTF/*.otf ~/.fonts/
    fc-cache -f -v
    rm -rf source-code-pro-1.017R/ 1.017R.zip
  args:
    creates: "~/.fonts/SourceCodePro-Bold.otf"

- name: "remove unnecessary dirs @ home"
  file:
    path="/home/renan/{{ item }}"
    state="absent"
  with_items:
    - Documents
    - Music
    - Videos
    - Templates
    - Public
    - Desktop

- name: "setup gsettings"
  become: false
  shell: |
    diff <(gsettings get {{item.setting}}) \
         <(gsettings set {{item.setting}} "{{ item.value }}"; \
           gsettings get {{item.setting}})
  args:
    executable: /bin/bash
  register: gsetting
  changed_when: gsetting.rc != 0
  failed_when: false
  with_items:
    - setting: "org.gnome.crypto.cache gpg-cache-method"
      value: "'timeout'"
    - setting: "org.gnome.crypto.cache gpg-cache-ttl"
      value: "10800"

    - setting: "org.gnome.Terminal.Legacy.Settings default-show-menubar"
      value: "false"

    - setting: "org.gnome.desktop.peripherals.touchpad tap-to-click"
      value: "true"
    - setting: "org.gnome.desktop.peripherals.keyboard repeat-interval"
      value: "17"
    - setting: "org.gnome.desktop.peripherals.keyboard delay"
      value: "202"
    - setting: "org.gnome.desktop.input-sources xkb-options"
      value: "['ctrl:nocaps', 'compose:rctrl']"

    - setting: "org.gnome.mutter workspaces-only-on-primary"
      value: "false"
    - setting: "org.gnome.shell.overrides workspaces-only-on-primary"
      value: "false"

    - setting: "org.gnome.mutter dynamic-workspaces"
      value: "true"
    - setting: "org.gnome.shell.overrides dynamic-workspaces"
      value: "true"
    - setting: "org.gnome.desktop.interface clock-show-date"
      value: "true"

    - setting: "org.gnome.desktop.wm.keybindings minimize"
      value: "['<Super>h']"
    - setting: "org.gnome.desktop.wm.keybindings maximize"
      value: "[]"
    - setting: "org.gnome.desktop.wm.keybindings toggle-maximized"
      value: "['<Super>Up']"
    - setting: "org.gnome.desktop.wm.keybindings toggle-fullscreen"
      value: "@as ['<Super><Alt>Up']"
    - setting: "org.gnome.desktop.wm.keybindings close"
      value: "['<Super>q']"
    - setting: "org.gnome.desktop.wm.keybindings panel-main-menu"
      value: "['<Super>space']"
    - setting: "org.gnome.settings-daemon.plugins.media-keys search"
      value: "'<Super>space'"
    - setting: "org.gnome.shell.keybindings toggle-overview"
      value: "['<Super>space']"
    - setting: "org.gnome.shell.keybindings toggle-application-view"
      value: "['<Super>a']"
    - setting: "org.gnome.mutter.keybindings toggle-tiled-left"
      value: "['<Control><Super>Left']"
    - setting: "org.gnome.mutter.keybindings toggle-tiled-right"
      value: "['<Control><Super>Right']"
