- name: "install mongodb apt-key"
  apt_key:
    state="present"
    keyserver="keyserver.ubuntu.com"
    id="0C49F3730359A14518585931BC711F9BA15703C6"

- name: "setup up mongodb repository"
  apt_repository:
    repo="deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main"
    state="present"
    update_cache="yes"
    mode="644"

- name: "install older libssl"
  apt:
    deb="http://ftp.br.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb"

- name: "install mongodb"
  apt:
    name="mongodb-org"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
