- name: "install datastax repo apt-key"
  apt_key:
    state="present"
    url="https://debian.datastax.com/debian/repo_key"

- name: "set up datastax repository"
  apt_repository:
    repo="deb http://debian.datastax.com/datastax-ddc 3.2 main"
    state="present"
    update_cache="yes"
    mode="644"

- name: "install cassandra"
  apt:
    name="datastax-ddc"
    state="present"
    update_cache="yes"
    cache_valid_time="7200"
